### ISSUE TITLE
input data

### ISSUE THREAD

**Issue by Jingxibei** [marsbroshok/challenge_cnn_tf#1]
Could you tell me what input data you use?

**Comment by marsbroshok** [comment]
Hi @DedongZhang , it's from this repo https://github.com/liyongsea/challenge-data
You can also find this link in 'How to' readme section.

**Comment by Jingxibei** [comment]
thank you for your reply. I have checked the link. Seems like it just talks about some fact for ECG signal. And their code is for prepossessing the ECG signal. But they didn't mention where the signal comes from or what kind of resolution or format is working for this code. 
I try to use MIT-BIH database to reproduce your work. But it keeps giving me errors.
