### ISSUE TITLE
Can not find the input data 

### ISSUE THREAD

**Issue by rmokros** [marsbroshok/challenge_cnn_tf#2]
I can not find the imput data on the other project .....

**Comment by abhilash1in** [comment]
+1

**Comment by Jingxibei** [comment]
+1

**Comment by marsbroshok** [comment]
Sorry guys, but the owner of the data pull it off from the web. 
It is really disappointing, but I hope the code will be somehow helpful anyway.

**Comment by abhilash1in** [comment]
Will you be able to upload it?

**Comment by marsbroshok** [comment]
Sadly I'm not the owner and I don't have the copy of the data. Maybe try to contact owner directly at his repo: https://github.com/liyongsea/challenge-data
